bellingcat/auto-archiver

archivers/twitter_archiver.py

Change name=large to name=orig Twitter image quality.
See https://webtrickz.com/download-images-in-original-size-on-twitter/

Get Twitter original size image quality

---

storages/gd_storage.py

As per issue https://github.com/bellingcat/auto-archiver/issues/48 here is a fix to get the google drive implementation working properly.

Put in fix for leading / in Google Drive

---

auto_archive.py
configs/config.py
example.config.yaml

https://github.com/bellingcat/auto-archiver/issues/47
Would appreciate some guidance on the best way to import this into the config.py file. I've got it working, but not sure of edge cases. It does seem to work well if the config items are missing.

Added whitelist and blacklist for worsheets (not spreadsheet)

---

.gitignore
configs/config.py
create_update_test_oauth_token.py
example.config.yaml
storages/gd_storage.py

Have been using this code for a month and it seems good. Token refreshes are handled.
Also updated a 'trashed = false' query for google drive so nothing in the recycle bin of google drive is picked up.

Oauth integration with Google Drive so can use a real user and not a service account

---

Dockerfile
Pipfile
Pipfile.lock
docker-entrypoint.sh
src/auto_archiver/enrichers/wacz_enricher.py

WACZ support with Docker

---

Dockerfile
Pipfile
Pipfile.lock

related to https://github.com/bellingcat/auto-archiver/issues/86
decided to do a better clean up so that projects that depend on auto-archiver don't depend on pywb

browsertrix dependencies isolated into dockerfile

---

src/auto_archiver/archivers/youtubedl_archiver.py

A good example is Song2 by Blur in a playlist: https://www.youtube.com/watch?v=WlAHZURxRjY&list=PL7A55EB715FBB2940&index=7

Added noplaylist true to youtubedl so that videos in playlists will work

---

src/auto_archiver/formatters/html_formatter.py

Set _mimetype for final media of html formatter

---

Pipfile.lock
src/auto_archiver/archivers/twitter_api_archiver.py
src/auto_archiver/enrichers/__init__.py
src/auto_archiver/enrichers/meta_enricher.py
src/auto_archiver/enrichers/wacz_enricher.py
src/auto_archiver/formatters/templates/html_template.html
src/auto_archiver/storages/s3.py
src/auto_archiver/version.py

- multiple twitter api keys supported
- improved de-duplication in S3
- meta_enricher to include file size and archive duration
- wacz extract only screenshot feature

0.8.0 new features and dependency updates

---

src/auto_archiver/storages/gd.py

The functionality using GDrive with service account is not working, due to loading config from the yaml is not right.

fix: Correct the path of service account in google drive settings

---

src/auto_archiver/databases/api_db.py

Change submit-archive from basic to bearer auth

---

src/auto_archiver/archivers/twitter_archiver.py
todo.md

Free Twitter strategies are tried in specific order: yt-dlp, snscrape, syndication and results are returned on the first successful execution. cc @djhmateer

refactors free twitter archiver strategies

---

src/auto_archiver/enrichers/wayback_enricher.py

I had this code written but it was not pushed before, followed hack into the wayback machine and consequent failed responses from their API.

adds better debug for wayback failures

---

example.orchestration.yaml
src/auto_archiver/enrichers/screenshot_enricher.py
src/auto_archiver/formatters/templates/html_template.html
src/auto_archiver/formatters/templates/macros.html
src/auto_archiver/utils/webdriver.py

Uncomment / copy the config options in `example.orchestration.yml` to save as a pdf. Some example print_options are set there.

Add 'print_pdf' option to the screenshot enricher. Fixes #132

---

.github/workflows/docker-publish.yaml
.github/workflows/python-publish.yaml
Dockerfile

Update actions for PyPi and Docker publish workflows.
Update Geckodriver version in Dockerfile (but still getting an error on the enricher)

Update versions for GH Actions and Geckodriver.

---

Dockerfile
src/auto_archiver/enrichers/wacz_enricher.py

- Had to switch to poetry-venv in dockerfile for it to build. 
- `blockAds` seems to interfere with cloudflare bot prevention, so I'm removing it for now

modifies base docker image to use browsertrix 1.4.2

---

CONTRIBUTING.md
README.md
docs/source/development/docs.md
docs/source/how_to.md

Now that the live docs have built, need to update the links

Fix links to docs

---

src/auto_archiver/core/orchestrator.py
src/auto_archiver/modules/instagram_tbot_extractor/instagram_tbot_extractor.py

Cleanup fixes

---

.github/workflows/tests-core.yaml
docs/source/development/release.md
poetry.lock
pyproject.toml

Update the version for the release to 0.13.5.
Update the description in the docs.

Update the release process docs and the latest version in pyproject.toml

---

.pre-commit-config.yaml
docs/source/development/style_guide.md
pyproject.toml

See #250 
Also: version bump for next release

Fix pre-commit for ruff check

---

docs/source/development/docs.md

Add info on building RTD versions + automated building of tagged versions

---

src/auto_archiver/modules/generic_extractor/dropin.py
src/auto_archiver/modules/generic_extractor/facebook.py
src/auto_archiver/modules/generic_extractor/generic_extractor.py
src/auto_archiver/modules/generic_extractor/tiktok.py
tests/conftest.py
tests/extractors/test_tiktok_tikwm_extractor.py

Makes it easier to maintain/understand.
Also fixies the issues with some tiktok links still not working.

Refactor the dropin 'is_suitable' method + fix for tikwm

---

src/auto_archiver/modules/generic_extractor/generic_extractor.py

Youtube videos were getting 'no archiver' result.

Small fix for generic_extractor.py for general/ youtube extraction.

---

docker-compose.yaml
src/auto_archiver/core/module.py
src/auto_archiver/modules/wacz_extractor_enricher/__manifest__.py
src/auto_archiver/modules/wacz_extractor_enricher/wacz_extractor_enricher.py
tests/enrichers/test_wacz_enricher.py
tests/test_modules.py

Wacz minor adjustments

---

.github/workflows/tests-core.yaml
.github/workflows/tests-download.yaml
src/auto_archiver/core/orchestrator.py
src/auto_archiver/modules/gsheet_feeder_db/gsheet_feeder_db.py
src/auto_archiver/modules/telethon_extractor/telethon_extractor.py

Small change to update version comparison check.

Small code fixes and GH Actions cache

---

src/auto_archiver/modules/instagram_tbot_extractor/instagram_tbot_extractor.py
tests/extractors/test_instagram_tbot_extractor.py

Added a check for empty responses from instagram_tbot_extractor.
Also bumped the minimum wait time for loading.

Only return success for instagram_tbot_extractor.py with content.

---

.github/workflows/tests-core.yaml
.github/workflows/tests-download.yaml
.gitignore
docs/source/installation/authentication.md
src/auto_archiver/core/base_module.py
src/auto_archiver/core/orchestrator.py
src/auto_archiver/modules/antibot_extractor_enricher/__manifest__.py
src/auto_archiver/modules/antibot_extractor_enricher/antibot_extractor_enricher.py
src/auto_archiver/modules/antibot_extractor_enricher/dropin.py
src/auto_archiver/modules/antibot_extractor_enricher/dropins/vk.py
src/auto_archiver/modules/generic_extractor/__manifest__.py
src/auto_archiver/modules/generic_extractor/generic_extractor.py
src/auto_archiver/utils/misc.py
tests/extractors/test_antibot_dropin_vk.py
tests/extractors/test_antibot_extractor_enricher.py

- Antibot can now have Dropins for specifc websites
- Introduces the VkDropin that replaces the recently lost feature of VK Scraperr

Introduces more flexibility to the Antibot Extractor

---

scripts/settings/package-lock.json
scripts/settings/package.json
scripts/settings/src/App.tsx
scripts/settings/src/StepCard.tsx

- dependabot
- Grid2 > Grid in material icons lib for react

fix to configuration editor npm versions
