bellingcat/auto-archiver

- README.md
The original instructions specified putting the gspread credentials file in the default location, but the code looks for a file in another place. The README now reflects the code's behavior.
> Changed instructions on creating credential files

- archivers/base_archiver.py
- archivers/telethon_archiver.py
- auto_archive.py
- storages/s3_storage.py
```
2022-03-18 11:06:22.340 | ERROR    | __main__:process_sheet:134 - Got unexpected error in row 2879 with archiver TelethonArchiver for url [...]: 'NoneType' object has no attribute 'grouped_id'
Traceback (most recent call last):
File "/Volumes/Oxygen/auto-archiver/auto_archive.py", line 131, in process_sheet
result = archiver.download(url, check_if_exists=True)
File "/Volumes/Oxygen/auto-archiver/archivers/telethon_archiver.py", line 65, in download
media_posts = self._get_media_posts_in_group(chat, post)
File "/Volumes/Oxygen/auto-archiver/archivers/telethon_archiver.py", line 41, in _get_media_posts_in_group
if post.grouped_id == original_post.grouped_id and post.media is not None:
AttributeError: 'NoneType' object has no attribute 'grouped_id'
```
> Resolve telethon issues

- archivers/youtubedl_archiver.py
Could probably remove the wwww as `in` will always match on facebook.com.
https://stackoverflow.com/questions/3437059/does-python-have-a-string-contains-substring-method
> Fixed wwww (4 w's) to www in youtubedl

- auto_archive.py
To help in production I've added in these levels of logging, and the 'catch all' decorator on main.
I've tried to adhere to standard logging levels:
https://github.com/djhmateer/djhmateer.github.io/blob/master/_posts/2022-04-25-loguru.md
And put in the top level catch all which is useful when Google API sometimes doesn't work querying the Google Sheet
> Add Logging output to logs folder

- .gitignore
- auto_archive.py
- auto_auto_archive.py
- configs/config.py
- example.config.yaml
If more than one auto-archivers were executed on the same folder with the same `tmp_folder` the 1st to finish would delete the folder and the other would not be able to upload any file, this PR removes that configuration completely and uses python's tempfile which is the advisable approach.
> refactor tmp folder logic due to concurrency issue

- .gitignore
- README.md
- archivers/base_archiver.py
- archivers/telegram_archiver.py
- archivers/telethon_archiver.py
- archivers/tiktok_archiver.py
- archivers/twitter_api_archiver.py
- archivers/twitter_archiver.py
- archivers/vk_archiver.py
- archivers/wayback_archiver.py
- archivers/youtubedl_archiver.py
- auto_archive.py
- configs/browsertrix_config.py
- configs/config.py
- example.config.yaml
- storages/s3_storage.py
- utils/gworksheet.py
The [browsertrix-crawler] utility is a browser-based crawler that can crawl one or more pages. browsertrix-crawler creates archives in the [WACZ] format which is essentially a standardized ZIP file (similar to DOCX, EPUB, JAR, etc) which can then be replayed using the [ReplayWeb.page] web component, or unzipped to get the original WARC data (the ISO standard format used by the Internet Archive Wayback Machine).
This PR adds browsertrix-crawler to archiver classes where screenshots are made. The WACZ is uploaded to storage and then added to a new column `WACZ` in the spreadsheet. Another column `ReplayWebPage` is also added that will display the WACZ, loaded from cloud storage (S3, DigitalOcean, etc) using the client side [ReplayWebPage](https://replayweb.page) application. You can see an …
> browsertrix crawler

- example.orchestration.yaml
Added an example config section for csb_db to the example.orchestration.yaml file to clarify how to store info about what's been archived and also stores the archive result in a csv datastore
> add csb_db config section to example.orchestration.yaml

- Pipfile.lock
- src/auto_archiver/utils/url.py
- src/auto_archiver/utils/webdriver.py
Closes #103 
Selenium has removed support for the headless option, this PR changes the archiver to use the new `--headless` argument.
They talk about the change [on their blog](https://www.selenium.dev/blog/2023/headless-is-going-away/), and made the change in [this commit](https://github.com/seleniumhq/selenium/commit/b5cfcc4f9c51dd9df9106b62971c417a0fc9a5e4).
This should be tested before merging.
> Fix Selenium headless invokation

- Pipfile
- src/auto_archiver/enrichers/wacz_enricher.py
The enricher already passes the --text flag to browsertrix. This commit extracts and exposes it in the result metadata.
MVP for #107
> Extract text in wacz_enricher

- .gitignore
- README.md
- src/auto_archiver/core/media.py
- src/auto_archiver/core/metadata.py
- src/auto_archiver/core/orchestrator.py
- src/auto_archiver/databases/__init__.py
- src/auto_archiver/databases/atlos_db.py
- src/auto_archiver/enrichers/whisper_enricher.py
- src/auto_archiver/feeders/__init__.py
- src/auto_archiver/feeders/atlos_feeder.py
- src/auto_archiver/storages/__init__.py
- src/auto_archiver/storages/atlos.py
- src/auto_archiver/storages/storage.py
- src/auto_archiver/utils/__init__.py
- src/auto_archiver/utils/atlos.py
- src/auto_archiver/version.py
This pull request adds a direct integration between Atlos (using some very new yet-undocumented API endpoints that are only available on our staging instance) and the auto archiver.
TODO:
@msramalho, if you have time it would be very helpful if you could just take a quick look at this PR and let me know if you see any blaring issues/architectural decisions you'd change.
I did have to make some small changes to the way that storages access metadata, as it's necessary for us to have the metadata in order to know where to store each piece of media.
> Add direct Atlos integration

- example.orchestration.yaml
- src/auto_archiver/archivers/youtubedl_archiver.py
Settings can be adjusted in orchestration.yml, with one of two options:
```
```
Todo: create a PR template, to ensure the following are done:
1. Tests passing
2. Documentation updated [need documentation guideline - do we put documentation in orchestration.yml or in command line args config description?
3. Reviewer (at least 1 other person)
> Allow setting cookies for yt-dl

- example.orchestration.yaml
- src/auto_archiver/archivers/__init__.py
- src/auto_archiver/archivers/archiver.py
- src/auto_archiver/archivers/bluesky_archiver.py
- tests/__init__.py
- tests/archivers/__init__.py
- tests/archivers/test_bluesky_archiver.py
- avoids ATProto
- leaves a few TODOs in reusable download_from_url method
> adds an unauthenticated Bluesky archiver

- src/auto_archiver/archivers/twitter_archiver.py
- tests/archivers/test_archiver_base.py
- tests/archivers/test_bluesky_archiver.py
- tests/archivers/test_twitter_archiver.py
This removes snscrape from the twitter archiver
1. snscrape twitter downloader no longer works (ref: https://github.com/JustAnotherArchivist/snscrape/issues/1045)
2. snscrape limits python to versions <3.12
Note: this only removes snscraper from the code, and not from the project. As we are switching to poetry, I have not touched the pipenv files so as to avoid merge confliccts. @erinhmclark if you agree, then you can remove snscrape from the new poetry config files in your PR :)
Note: this PR also contains:
1. Some small updates to the test classes for achivers (starting to create a base class). Note this does not yet separate code tests and response validation. That is WIP
2. Fixes a potential bug whereby tweets archived by the twitter_archiver, using ytdlp aren't marked as …
> Remove snscrape from the twitter_archiver

- src/auto_archiver/archivers/twitter_archiver.py
- src/auto_archiver/formatters/templates/macros.html
- tests/archivers/test_twitter_archiver.py
These are some small issues I came across whilst setting up/testing the project. I will add to this PR if I find any more. For bigger issues/features, I'll create new issues.
> Fix two small issues

- README.md
- docker-compose.yaml
Just use `docker compose up` to build and run. It'll only regenerate an image if
> Add docker-compose for easy building and running of docker image in dev

- .github/workflows/tests-core.yaml
- poetry.lock
- pyproject.toml
- src/auto_archiver/archivers/generic_archiver/generic_archiver.py
tests on ubuntu-latest are currently failing, due to the issue in oscrypto: https://github.com/wbond/oscrypto/issues/78#issuecomment-1756317472
Not sure if we want to merge this in, or wait for a solution before we merge
> Add ubuntu-latest to the matrix of test runners

- src/auto_archiver/core/orchestrator.py
- tests/extractors/test_twitter_api_extractor.py
@msramalho  - this should hopefully fix the issue.
You should still be able to use run() now, or alternatively you can use:
```python
from auto_archiver.core.orchestrator import ArchivingOrchestrator
orchestrator = ArchivingOrcestrator()
orchestrator.setup(["--config", "whatever", "--other-things"])
for item in orchestrator.feed():
```
> Fix generator

- src/auto_archiver/modules/instagram_extractor/__manifest__.py
- src/auto_archiver/modules/instagram_extractor/instagram_extractor.py
- tests/extractors/test_instagram_extractor.py
The instagram_extractor had a typo left from the updated config method.
This PR fixes the typo and adds a warning to the documentation mentioning that it isn't being maintained, and that the other instagram extraction methods should be preferred.
See issue:
https://github.com/bellingcat/auto-archiver/issues/231
> Instagram extractor bugfix

- Dockerfile
- src/auto_archiver/core/base_module.py
- src/auto_archiver/modules/screenshot_enricher/__manifest__.py
- src/auto_archiver/utils/webdriver.py
This downloads the correct version of geckodriver depending on the Docker arch, fixing #232 
This was only an issue for people running on Mac with M1 chips.
Personally, I still vote for doing away with multiple archs for easier maintenance. Sure, maybe for Mac users (and linux ARM users - are there many?) it'll mean a slightly slower run, but 🤷‍♂️
If we remove ARM builds, it'll also a) speed up the docker build and b) mean we can remove the geckodriver update dance (selenium supports geckodriver for linux x86 out of the box)
> Docker webdriver aarch64

- src/auto_archiver/core/orchestrator.py
- src/auto_archiver/modules/console_db/console_db.py
- src/auto_archiver/modules/generic_extractor/__manifest__.py
- src/auto_archiver/modules/generic_extractor/generic_extractor.py
1. Checks yt-dlp for updates every X days (based on `ytdlp_update_interval` in settings). If an update is available, it automatically updates
2. Checks for auto-archiver updates on every run (it's a single http request, I think it's fine) and provides a warning to the user and a command on how they can update
> Auto Updates

- .github/workflows/docker-publish.yaml
Following the discussion in the issue here: https://github.com/bellingcat/auto-archiver/issues/212
This PR adds cache-from and cache-to to the docker-publish GH Actions workflow.
This should significantly reduce the build time.
The stats so far seem to be:
Push with no change: <1 min
Push with code change: ~4 mins
Push with requirements change: ~17 mins
> Add cache-from and cache-to to docker-publish.yaml.

- README.md
- src/auto_archiver/modules/api_db/__manifest__.py
- src/auto_archiver/modules/tiktok_tikwm_extractor/__init__.py
- src/auto_archiver/modules/tiktok_tikwm_extractor/__manifest__.py
- src/auto_archiver/modules/tiktok_tikwm_extractor/tiktok_tikwm_extractor.py
- tests/extractors/test_tiktok_tikwm_extractor.py
closes https://github.com/bellingcat/auto-archiver/issues/215
uses an unofficial API to capture videos that generic_extractor cannot capture without cookies or other authentication data.
> Adds new extractor for tiktok via unofficial API

- src/auto_archiver/core/config.py
- src/auto_archiver/core/consts.py
- src/auto_archiver/core/extractor.py
- src/auto_archiver/core/media.py
- src/auto_archiver/core/orchestrator.py
- src/auto_archiver/core/storage.py
- src/auto_archiver/modules/cli_feeder/cli_feeder.py
- src/auto_archiver/modules/local_storage/local_storage.py
- src/auto_archiver/modules/s3_storage/s3_storage.py
- tests/enrichers/test_pdq_hash_enricher.py
- tests/storages/test_S3_storage.py
- tests/storages/test_atlos_storage.py
- tests/storages/test_gdrive_storage.py
- tests/storages/test_local_storage.py
- tests/storages/test_storage_base.py
Fixes #228 
More importantly, I also found a bug in the base `Storage` class that meant the storage settings (like path_generator and file_generator) weren't being honoured.
I've fixed that + added unit tests.
It turns out, this 'filename too long' bug could appear for *any* storage type, we probably haven't seen it with S3 because they have a max file length of 1024 chars. But I've implemented a generic way to cut the length of file names. I'm not sure if it's the best way to do it.
Also for discussion: there's a line of code here when path_generator = 'flat' that sets the filename, but then that's never used (since it'll be overridden a few lines later if file_generator is random/static). 
Do we ever have a situation where we want the filename to be `slugify(path)` ? Right now the only …
> Unit tests for storage types + fix storage too long issues for local storage

- src/auto_archiver/core/module.py
- src/auto_archiver/core/orchestrator.py
- src/auto_archiver/modules/generic_extractor/twitter.py
- tests/data/test_modules/example_extractor/__manifest__.py
- tests/data/test_modules/example_extractor/example_extractor.py
- tests/extractors/test_generic_extractor.py
- tests/test_orchestrator.py
Fixes an issue seen on discord where a user accidentally set up metadata_enricher under 'extractors'
https://discord.com/channels/709752884257882135/1346596825611632770/1351336725070483477
To reproduce/test add 'gsheets_db_feeder' to 'extractor' step (or any other module to the wrong step)
Edit: Also fixes a small bug I saw in the Twitter dropin
> When loading modules, check they have been added to the right 'step' in the config

- src/auto_archiver/modules/generic_extractor/__manifest__.py
- src/auto_archiver/modules/generic_extractor/generic_extractor.py
- tests/test_modules.py
Add option to add any [extractor args](https://github.com/yt-dlp/yt-dlp/blob/master/README.md#extractor-arguments) to the generic extractor.
This was added in preparation for passing proof of origin tokens, but separating it into it's own PR.
> Add flexible extractor_args to generic_extractor.py

- pyproject.toml
- src/auto_archiver/core/base_module.py
- src/auto_archiver/modules/instagram_extractor/instagram_extractor.py
- src/auto_archiver/modules/screenshot_enricher/screenshot_enricher.py
- src/auto_archiver/utils/url.py
- src/auto_archiver/utils/webdriver.py
- tests/enrichers/test_screenshot_enricher.py
- tests/utils/test_urls.py
This:
* Adds unit tests for utils/url
* Fixes a bug in the webdriver - it was looking for `cookies` in the auth dict, but it should be `cookie` and adds the 'removeprefix' back in, I'd accidentally removed it on the cookies check.
* Provides better logs when auth isn't supported (if a user tries to do username/password login with the screenshot enricher)
> Minor fixes

- poetry.lock
- pyproject.toml
pyOpenSSL also no longer needed - that was needed for the old timestamping enricher and is what was keeping cryptography back.
Fixes #277 
For more info on dependabot warning, see: https://github.com/bellingcat/auto-archiver/security/dependabot/73
> This force-pins cryptography to >44.0.1 to fix dependabot warning

- .github/workflows/tests-download.yaml
- src/auto_archiver/core/module.py
I realised my previous CI changes didn't work correctly because it was set to `branches: [main]` only.
This hopefully fixes that, meaning the download CI tests run after the core tests have passed.
> Download tests

- src/auto_archiver/core/module.py
- src/auto_archiver/core/orchestrator.py
- src/auto_archiver/core/validators.py
- src/auto_archiver/modules/telethon_extractor/__manifest__.py
- src/auto_archiver/modules/telethon_extractor/telethon_extractor.py
- tests/conftest.py
- tests/data/test_modules/example_extractor/example_extractor.py
- tests/data/test_modules/example_module/example_module.py
- tests/extractors/test_generic_extractor.py
- tests/extractors/test_telethon_extractor.py
- tests/test_orchestrator.py
Don't add/remove .session from name, keep the file name without .session at all times
Fixes https://github.com/bellingcat/auto-archiver/issues/260 
Previously - the `lazy_module.load(self.config)` code in orchestrator.py:L386 was not returning a `loaded_module` which meant the cleanup was never called. Now we check if the instance has been created instead of if the module has been loaded - makes sure `cleanup` is always called.
> Fix calling extractor.cleanup (fixes telethon issue) + tidy up telethon extractor session file naming

- .github/workflows/tests-download.yaml
It wasn't properly being triggered after the core tests. this reverts so that the download tests just run all for every PR as it was previously
> Revert downloads CI tests changes

- src/auto_archiver/modules/gsheet_feeder_db/gsheet_feeder_db.py
Have started exploring the new excellent v1 release, and thought I'd do very small PR's of tweaks. Feel free to ignore if I've misunderstood anything.
In this case I feel that starting a run is more of an information level.
> Changed log level on gsheet_feeder_db started from warning to info

- docs/source/development/style_guide.md
ruff-fix -> ruff-clean; there is no ruff-fix in the default Makefile. Maybe the command /should/ be ruff-fix to align with the underlying ruff command; that might be for a later discussion. This at least reconciles the documentation to the default Makefile
> updating the style-checking code in the documentation
